# TOML file for generating the applecrate package with applecrate
# The version in this file will be updated by bump2version

app = "makelive"
version = "0.6.0"
identifier = "org.rhettbull.makelive"
license = "LICENSE"
install = [
    [
        "build/makelive-0.6.0-{{ machine }}",
        "/usr/local/bin/makelive",
    ],
]
pre_install = "scripts/preinstall.sh"
output = "dist/{{ app }}-{{ version }}-{{ machine }}-installer.pkg"
sign = "$DEVELOPER_ID_INSTALLER"
